### ISSUE TITLE
What is progress of standatizing open pattern matching and/or open multimethods?

### ISSUE THREAD

**Issue by Talkless** [solodon4/Mach7#57]
Hi,

I have just watched video of "Accept No Visitors" talk and was really impressed!

There was mentioned will to standardise these techniques, which would be really nice to have this language feature with low-level performance and yet high level abstractions!

Is there any progress with that? Was there a proposal submitted or drafted (not sure where to browse for these)? What are comments from other committee members?

Thanks!

**Comment by kirbyfan64** [comment]
AFAIK the only related proposal is [P0051R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0051r0.pdf), which actually references a paper about Mach7.

**Comment by solodon4** [comment]
That is correct, there is currently no proposal based on this, mostly because of time issues with my daily work on Visual C++ and Clang/C2. I am trying to put things together and hopefully present them at one of the C++ conferences, but that goes very slowly unfortunately as I have other things contending for my free time as well. I'll post any updates when they become available on the project page and in the comments here, please stay tuned.

**Comment by Talkless** [comment]
Thanks @kirbyfan64 and @solodon4 and good luck!
